### ISSUE TITLE
[v3] firestack.database() is not a function error - documentation error

### ISSUE THREAD

**Issue by tam-borine** [fullstackreact/react-native-firestack#200] opened 2016-12-27 14:51 UTC
In several places in .md files for this library, `firestack.database().ref('someNode/')...` is recommended but I kept getting an error that firestack.database() was not a function. I opened the firestack object and indeed couldn't find such a function. I had to go into FirestackApp, the example working app, to see how they had done it just to realise that `firestack.database.ref('someNode/')...`  - ie. without trying to invoke firestack.database ...works... 

This is where the objective is simply to write an entry to database.

**Comment by tam-borine** [comment] 2016-12-27 14:51
I would try to update docs myself and make a PR but it's in multiple places and also in Salakar's fork and maybe others so thought I'd make an Issue for now and see what people think.

**Comment by Salakar** [comment] 2016-12-29 11:51
@tam-borine v3 branch on here has been re-synced with my fork - the docs should be correctly saying to use `database()` - main point of my fork is to have it match the firebase web api - so the docs can therefore be minimal. \o/

I believe @Ehesp was also doing some work on the docs?

**Comment by smkhalsa** [comment] 2016-12-31 17:36
@Salakar I've been using the firebase JS library as follows...

```
import firebase from 'firebase'
import config from './firebaseConfig'

firebase.initializeApp(config)

export const albumsRef = firebase.database().ref('albums/v1-0')
```

I just tried  pulling down the v3 branch and swapping out `firebase` for `react-native-firebase`:

```
import firebase from 'react-native-firestack'
import config from './firebaseConfig'

firebase.initializeApp(config)

export const albumsRef = firebase.database().ref('albums/v1-0')
```

However, I'm getting an error `_reactNativeFirestack2.default.database is not a function`

I tried deleting my `node_modules` folder and reinstalling as well as `react-native unlink` / link, but the problem persists. Is there any additional config that I need to do in the v3 branch?

**Comment by Salakar** [comment] 2017-01-02 09:38
@smkhalsa it's not swapped out correctly, you need to empty the existing dir before pulling down - otherwise there's a mash of files.  e.g. `database.js` vs `database/index.js`

**Comment by esdrasportillo** [comment] 2017-01-03 11:19
@Salakar Do you know when it will be released? 
Thanks.

**Comment by smkhalsa** [comment] 2017-01-07 19:40
@Salakar I'm not sure I understand. I've deleted my entire node_modules dir and unlinked / linked react-native-firestack, but I still get this error.

**Comment by moooji** [comment] 2017-01-09 05:27
`database.js` seems to be still in the v3 repo and overrides `database/index.js` See here: https://github.com/fullstackreact/react-native-firestack/blob/v3/lib/modules/database.js

This is also the cause for this issue: https://github.com/fullstackreact/react-native-firestack/issues/220

**Comment by Salakar** [comment] 2017-01-09 11:51
@moooji see https://github.com/fullstackreact/react-native-firestack/issues/220#issuecomment-271256869

**Comment by moooji** [comment] 2017-01-10 23:37
Looks like `database.js` has been removed by @auser in the v3 repo. I guess this can be closed now.

**Closed** 2017-01-11 18:24 UTC
Labels: docs
