### ISSUE TITLE
orderByChild not working

### ISSUE THREAD

**Issue by tegument** [fullstackreact/react-native-firestack#82] opened 2016-10-22 15:41 UTC
I have items stored in firebase with a 'createdAt' property which is the server TIMESTAMP.  The TIMESTAMP value is being set correctly, but when querying using orderByChild('createdAt') the order is not correct.

I have verified that the same query run with the firebase javascript API works as expected:

`firestack.database.ref('images').orderByChild('createdAt').once('value', (snapshot)=>{
   // snapshot not ordered by correctly
});`

Firebase javascript API:

`firebaseApp.database().ref('images').orderByChild('createdAt').once('value', (snapshot)=>{
  // snapshot ordered correctly
});`

I have an index set in my firebase rules but can't seem to get Firestack to use the orderByChild query

**Comment by tegument** [comment] 2016-10-22 16:00
If I use the following query the result is in the correct order:

`fsImageRef.orderByChild('createdAt').on("child_added", function(snapshot) {
        console.log(snapshot.val().createdAt);
      });`

Am I not using the correct method?  I just need to load all by createdAt

**Comment by auser** [comment] 2016-10-23 11:10
What platform are you testing it on or is it both (iOS/Android)?

**Comment by tegument** [comment] 2016-10-23 13:34
Android only.

I'm also having the same issue with the following query:

Works with Firebase JS API:
`imagePageRef = firebaseApp.database().ref('feeds/'+uid).orderByChild('createdAt').endAt(lastItemKey).limitToLast(pageCount + 1);`

Doesn't work with Firestack:
`imagePageRef = firestack.database.ref('feeds/'+uid).orderByChild('createdAt').endAt(lastItemKey).limitToLast(pageCount + 1);`

Firestack doesn't return correct order and when calling again to get next 'page' of posts based on the last item key endAt it ignores this and returns that last items.

**Comment by auser** [comment] 2016-10-23 13:36
Great. I'll take a look... thanks for reporting!

**Comment by tegument** [comment] 2016-10-23 13:37
Np! I'd love to help troubleshoot this further and looked through the JS/Java to see if I could find anything.  Please let me know what you find so I can possibly be a better help in the future haha

**Comment by tegument** [comment] 2016-10-23 13:41
I haven't been testing on iOS yet, but if I do i'll let you know.

**Comment by auser** [comment] 2016-10-25 16:12
I found it, I think. I haven't been able to test it yet, but I'm pretty certain I know the issue

**Comment by tegument** [comment] 2016-10-25 23:21
Awesome! let me know if you have a patch and I can test it out

**Comment by auser** [comment] 2016-10-26 11:47
@tegument I just pushed a branch called `feature/query`. Can you try it out there?

**Comment by tegument** [comment] 2016-10-26 12:51
i'm using the following query:

`imagePageRef = firestack.database.ref(dbPath).orderByChild('createdAt').endAt(lastItemKey).limitToLast(itemsPerPage + 1);`

but receive the following error:

"You can't combine multiple orderBy calls!"

![capture](https://cloud.githubusercontent.com/assets/1362670/19726542/46a0aeb0-9b40-11e6-8acd-a25ccd168c4c.JPG)

**Comment by auser** [comment] 2016-10-31 02:43
Yes. I know the fix for this. Apologies about the delay. I've been jet lagged from my trip!

**Comment by jsappme** [comment] 2016-11-01 16:10
It does not work with iOs either

**Comment by chaitanya0bhagvan** [comment] 2016-11-12 20:13
@auser I too encountered this issue and after debugging I found that the orderByChild is passed to firebase and the response is indeed sorted on the key specified. The order is getting lost in `FirestackUtils.castSnapshotValue` Seems like `WritableMap` does not maintain the order of insertion.

**Comment by auser** [comment] 2016-11-13 02:32
Oh yes. I added a map and for each function on snapshot to retain the order

Get Outlook for iOS




On Sat, Nov 12, 2016 at 12:13 PM -0800, "Chaitanya Bhagvan" <notifications@github.com> wrote:












@auser I too encountered this issue and after debugging I found that the orderByChild is passed to firebase and the response is indeed sorted on the key specified. The order is getting lost in FirestackUtils.castSnapshotValue Seems like WritableMap does not maintain the order of insertion.

**Comment by chaitanya0bhagvan** [comment] 2016-11-13 07:23
@auser I am not sure I understand what you mean.

**Comment by chaitanya0bhagvan** [comment] 2016-11-13 13:30
@auser I got what you were saying. But the problem is not in the iteration, it's in WritableMap. When new key/values are pushed it does not maintain the insert order. The solution I can think of is to use a JSON Writer to construct the response.

**Comment by auser** [comment] 2016-11-13 16:25
It's not about iterating. The way forEach and map work is by using the ordered keys in response. The response, if contains keys returns with objects with keys, the native side returns the list of keys as an ordered array. 
In JS, we have those iterables to handle the looping in order. Feel free to check the implementation for more details. 



On Sun, Nov 13, 2016 at 5:30 AM -0800, "Chaitanya Bhagvan" <notifications@github.com> wrote:












@auser I got what you were saying. But the problem is not in the iteration, it's in WritableMap. When new key/values are pushed it does not maintain the insert order. The solution I can think of is to use a JSON Writer to construct the response.

**Comment by auser** [comment] 2016-11-13 16:48
By the way, this is the same approach as the web library takes to handle ordering.

**Closed by auser** 2016-11-13 16:48 UTC

**Comment by chaitanya0bhagvan** [comment] 2016-11-14 07:34
@auser If I understand correctly then you are saying the response is an ordered array, but the snapshot.value or snapshot.val() is an object and does not have map or forEach methods on it.

**Comment by chaitanya0bhagvan** [comment] 2016-11-14 07:46
@auser This happening only on android. iOS works just fine.

**Comment by auser** [comment] 2016-11-14 17:54
Not sure how it could... also I was talking about the master branch,  not npm. Js objects do not respect ordering on keys, so if it is working, it by happenstance.

**Comment by auser** [comment] 2016-11-14 17:55
Technically how we handle it is through storing the ordered list of keys and mapping through the array of keys in the forEach and map methods on the snapshot

**Comment by smkhalsa** [comment] 2016-12-01 00:25
@auser I'm having this issue on iOS. 

I believe there is an issue with how data is being returned to JS in general, not just with the `orderByChild` method. In my firebase, I have some data with alphabetic keys such as the following:

- aa
- bb
- cc

In the data browser, it is ordered as above. If I request it with the web JS library, it comes back correctly in the above order. However, when I request this data via firestack, this order is not maintained. Even if I use the `orderByKey` method, the data still comes back shuffled. 

My first thought is that the shuffling might be happening when the data gets transferred from native to JS.

**Comment by smkhalsa** [comment] 2016-12-01 01:53
I should note that I'm using the npm version, not the latest from master

**Comment by florianbepunkt** [comment] 2016-12-01 17:08
I experience the same issue on V3 branch. orderByChild takes no effect…

**Comment by chaitanya0bhagvan** [comment] 2016-12-01 17:53
@smkhalsa @florianbepunkt Use the master branch. The one on npm does not have this feature.

**Comment by florianbepunkt** [comment] 2016-12-01 18:01
@chaitanya0bhagvan I created a new issue since I'm using v3 branch… maybe orderByChild is not implemented in this branch yet. #174

**Comment by auser** [comment] 2016-12-01 19:52
Not sure about the branch (yet), but I just pushed a new `npm` version (2.3.4), which includes this feature. Notice that the order is maintained _by_ the JS client through a `map` and `forEach` function as JS objects do not respect order. In order to keep order, you _have_ to use the JS function.

**Comment by florianbepunkt** [comment] 2016-12-01 20:07
@auser Thank you. I will wait and see if this is in Michael's branch which I'm using due to the different syntax. If not I will switch and rewrite my firestack calls.

You say we have to use the JS function. Is there any extra method involved or can we use something like

```
firestack
.ref('foo')
.orderby('bar').
.endAt('foo')
.once('value)
.then(…)
```

**Comment by smkhalsa** [comment] 2016-12-01 20:31
@auser Thanks! It looks like `npm` 2.3.4 fixed this for me.

**Comment by auser** [comment] 2016-12-02 00:17
@florianbepunkt it's a method on the database ref representation object, so it would happen in the `then` function.  Using your example:

```javascript
firestack
.ref('foo')
.orderby('bar').
.endAt('foo')
.once('value)
.then(ref => this.setState({items: ref.map(i => i)})); // the `map` returns the ordered keys. You can handle this yourself if you want to by iterating through the keys and finding the items associated with that key and setting the order yourself or just use the `map()` function.
```
