### ISSUE TITLE
orderByChild does not seem to work

### ISSUE THREAD

**Issue by jsappme** [fullstackreact/react-native-firestack#103] opened 2016-11-01 15:47 UTC
firebaseApp.database.ref('posts/').orderByChild('timestamp') does not return ranked result

**Comment by tegument** [comment] 2016-11-01 15:59
@jsappme this is a duplicate of #82

**Comment by auser** [comment] 2016-11-01 16:40
Which platform, @jsappme ?

**Comment by jsappme** [comment] 2016-11-01 17:24
it does not work with iOs

**Comment by auser** [comment] 2016-11-01 17:55
How are you storing the timestamps?

**Comment by auser** [comment] 2016-11-01 17:56
And happy to hop on screenhero to debug.

**Comment by jsappme** [comment] 2016-11-01 17:59
const time = Date.now()
        console.log(time);
        const uid = this.props.currentUser.uid;
        const name = this.props.currentUser.name;

        firebaseApp.database.ref('posts').push().then((res) => {
          let newPostKey = res.key;
          const postData = {
            name: name,
            timestamp: time * -1,
            text: this.state.postText,
            title: this.state.postTitle,
            puid: newPostKey
          }
          let updates = {}
          updates['/posts/' + newPostKey] = postData
          updates['/users/' + uid + '/posts/' + newPostKey] = postData
          firebaseApp.database.ref().update(updates).then(() => {
            this.setState({
                            postStatus: 'Posted! Thank You.',
                            postText: '',
                          });
          }).catch(() => {
            this.setState({ postStatus: 'Something went wrong!!!' });
          })
        })

**Comment by auser** [comment] 2016-11-01 18:12
Hm... It's working on [https://github.com/fullstackreact/FirestackApp](https://github.com/fullstackreact/FirestackApp).

Relevant code: [https://github.com/fullstackreact/FirestackApp/blob/master/app/views/Database/Demos/Chat.js](https://github.com/fullstackreact/FirestackApp/blob/master/app/views/Database/Demos/Chat.js)

**Comment by jsappme** [comment] 2016-11-01 18:17
using wich version of the repo?
 
npm or master?

**Comment by auser** [comment] 2016-11-01 18:17
Oh, `master`

**Comment by jsappme** [comment] 2016-11-01 18:20
it's not working on my side

**Comment by auser** [comment] 2016-11-01 18:27
Do you have screenhero? Want a second pair of eyes?

**Comment by jsappme** [comment] 2016-11-01 18:30
yes I would love to, I am stucked right now

**Comment by jsappme** [comment] 2016-11-01 18:31
I dont have screenhero sorry, how can I get it?

**Comment by auser** [comment] 2016-11-01 18:32
write me an email at ari [at] fullstack.io and I'll invite you. Fair warning, I'm sick, so it'll be more of a whisper.

**Closed** 2016-11-01 19:39 UTC
